# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formExample', '0002_college_college_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='college',
        ),
    ]
